steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/dicoding-mp/mentoring-platform-ml-api"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/dicoding-mp/mentoring-platform-ml-api"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "--image"
      - "gcr.io/dicoding-mp/mentoring-platform-ml-api"
